SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import Sion_Controller.urls as Sion_Controller

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Sion-Controller/', include(Sion_Controller,namespace='Sion-Controller')),
    url(r'^$', RedirectView.as_view(url='/Sion-Controller/',permanent = True)),
]

Sion_Controller/urls.py
from django.conf.urls import url
from .views import index, login, register_relawan, register_donatur, register_sponsor
from .custom_auth import auth_login, auth_logout
from .register_organisasi import register_organisasi, reg_organisasi
from .profile import profile_user

urlpatterns = [
    #Landing Page
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    #Register Organisasi
    url(r'^register_organisasi/$', register_organisasi, name='register-organisasi'),
	url(r'^reg_organisasi/$', reg_organisasi, name='reg-organisasi'),

	#Register Pengguna
	url(r'^register_Relawan/$', register_relawan, name='register-relawan'),
	url(r'^register_Donatur/$', register_donatur, name='register-donatur'),
	url(r'^register_Sponsor/$', register_sponsor, name='register-sponsor'),

	#Profile
	url(r'^profile/$', profile_user, name='profile'),
]

Sion_Controller/models.py
from django.db import models

# Create your models here.

Sion_Controller/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
response = {}

def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('Sion-Controller:profile'))
    else:
        response['login'] = False
        html = 'login/landing.html'
        return render(request, html, response)


def login(request):
    html = 'login/login.html'
    return render(request, html, response)

def register_relawan(request):
    html = 'register/register_relawan.html'
    return render(request, html)

def register_donatur(request):
    html = 'register/register_donatur.html'
    return render(request, html)

def register_sponsor(request):
    html = 'register/register_sponsor.html'
    return render(request, html)

Sion_Controller/templates/Berdonasi/donasi.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="theme.css" type="text/css"> </head>

<body>
  <div class="py-5 bg-primary">
    <div class="container">
      <div class="row">
        <div class="align-self-center col-md-6 text-white">
          <h1 class="text-center text-md-left display-3">Berdonasi Ke Organisasi</h1>
        </div>
        <div class="col-md-6">
          <div class="card">
            <div class="card-body p-5">
              <h3 class="pb-3">
                <b>Donasi</b>
              </h3>
              <form>
                <div class="form-group ">
                  <label>Organisasi</label>
                  <select class="form-control " syle="height:100px; width:auto; ">
                    <option>Organisasi-1</option>
                    <option>Organisasi-2</option>
                    <option>Organisasi-3</option>
                  </select>
                  <div class="form-group ">
                    <label>Jumlah Dana</label>
                    <input type="number " class="form-control " placeholder="Dana"> </div>
                </div>
                <a href="#" class="btn btn-outline-primary" data-toggle="modal" data-target="#donate-modal">Donate</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal" id="donate-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Donasi</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>×</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Apakah benar anda ingin berdonasi ke organisasi ini?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary">YES</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">NO
              <br> </button>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </div>
</body>

</html>

Sion_Controller/templates/login/landing.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body>
  <div class="py-5 text-center bg-gradient" style="height: 100%;background-position:center;background-size:cover;background-repeat:no-repeat;"">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="mb-4 text-white display-1">SION</h1>
          <h1 contenteditable="true">Sistem Informasi Organisasi Nirlaba</h1>
          <a href="{% url 'Sion-Controller:login' %}" class="btn btn-lg mx-1 btn-secondary">Log in</a>
          <p class="">
            <br>OR</p>
          <div class="btn-group">
            <button class="btn dropdown-toggle btn-outline-light" data-toggle="dropdown"> Register</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'Sion-Controller:register-relawan' %}">Relawan</a>
              <a class="dropdown-item" href="{% url 'Sion-Controller:register-donatur' %}">Donatur</a>
              <a class="dropdown-item" href="{% url 'Sion-Controller:register-sponsor' %}">Sponsor</a>
              <a class="dropdown-item" href="{% url 'Sion-Controller:register-organisasi' %}">Organisasi</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

Sion_Controller/templates/login/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body>
  <div class="py-5 bg-light" style="height: 100%;background-position:center;background-size:cover;background-repeat:no-repeat;background-image:url('{%static 'helpothers.jpeg' %}');">
    <div class="container">
      <div class="row">
        <div class="align-self-center col-md-6 text-white">
          <h3 class="display-1">SION</h3>
          <p class="lead">Sistem Informasi Organisasi Nirlaba</p>
        </div>
        <div class="col-md-6">
          <div class="card">
            <div class="card-body p-5">
              <form action="{% url 'Sion-Controller:auth_login' %}" method="POST">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Username" name="username" required="required"> </div>
                <div class="form-group">
                  <input type="password" class="form-control" name="password" placeholder="Password" required="required"> </div>
                <button type="submit" class="btn mt-2 btn-outline-success">Log in</button>
              </form>
              <div class="row">
                <div class="col-md-12">
                  <p class="lead">Tidak punya akun?
                    <br> </p>
                  <div class="btn-group">
                    <button class="btn dropdown-toggle btn-outline-success" data-toggle="dropdown"> Register</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'Sion-Controller:register-relawan' %}">Relawan</a>
                      <a class="dropdown-item" href="{% url 'Sion-Controller:register-donatur' %}">Donatur</a>
                      <a class="dropdown-item" href="{% url 'Sion-Controller:register-sponsor' %}">Sponsor</a>
                      <a class="dropdown-item" href="{% url 'Sion-Controller:register-organisasi' %}">Organisasi</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

Sion_Controller/templates/profile/profile_donatur.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-green.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <b class="">&nbsp;SION
            <br>
          </b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <a class="btn btn-primary" href="#">Pofile</a>
            <a class="btn btn-primary" href="#">Lihat Organisasi</a>
            <div class="btn-group">
              <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Donasi</button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Berdonasi ke Organisasi</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Berdonasi ke Kegiatan</a>
              </div>
            </div>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href="{% url 'Sion-Controller:auth_logout' %}">
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Log Out</a>
        </div>
      </div>
    </nav>
  </header>
  <content style="color: black;">
    <div class="w3-container w3-content w3-round" style="margin-top: 50px; width: 600px;">
      <div class="w3-card w3-round w3-white">
        <div class="text-center">
          <div class="bg-primary">
            <h4 class="w3-center" style="margin-bottom: 20px; padding-top: 15px;">{{nama}}r</h4>
            <div class="w3-theme-l4" style="height: auto; padding-top: 30px;">
              <button class="btn btn-primary" style="margin-bottom: 20px;">Saldo : Rp. {{saldo}}</button>
              <p><i class="fa fa-envelope fa-fw w3-margin-right w3-text-theme"></i>{{email}}</p>
              <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{alamat}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>


  </content>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>


</html>

Sion_Controller/templates/profile/profile_pengurusorganisasi.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-green.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <b class="">&nbsp;SION<br> </b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <a class="btn btn-primary" href="#">Pofile</a>
            <a class="btn btn-primary" href="#">Lihat Organisasi</a>
            <div class="btn-group">
              <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Kegiatan</button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Buat Kegiatan</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Lihat Kegiatan</a>
              </div>
            </div>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href="{% url 'Sion-Controller:auth_logout' %}">
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Log Out</a>
        </div>
      </div>
    </nav>
  </header>

  <content style="color: black;">
    <div class="w3-container w3-content w3-round" style="margin-top: 50px; width: 600px;">
      <div class="w3-card w3-round w3-white">
          <div class="text-center">
            <div class="bg-primary">
              <h4 class="w3-center" style="margin-bottom: 20px; padding-top: 10px;">{{nama}}</h4>
              <div class="w3-theme-l4" style="height: 150px; padding-top: 30px;">
                <p><i class="fa fa-envelope fa-fw w3-margin-right w3-text-theme"></i>{{email}}</p>
                <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i>{{alamat}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </content>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

Sion_Controller/templates/profile/profile_relawan.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-green.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <b class="">&nbsp;SION<br> </b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <a class="btn btn-primary" href="#">Pofile</a>
            <a class="btn btn-primary" href="#">Lihat Organisasi</a>
            <div class="btn-group">
              <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Donasi</button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Berdonasi ke Organisasi</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Berdonasi ke Kegiatan</a>
              </div>
            </div>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href="{% url 'Sion-Controller:auth_logout' %}">
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Log Out</a>
        </div>
      </div>
    </nav>
  </header>

  <content style="color: black;">
    <div class="w3-container w3-content w3-round" style="margin-top: 50px; width: 600px;">
      <div class="w3-card w3-round w3-white">
        <div class="text-center">
          <div class="bg-primary">
            <h4 class="w3-center" style="margin-bottom: 20px; padding-top: 15px;">{{nama}}</h4>
            <div class="w3-theme-l4" style="height: auto; padding-top: 30px;">
              <p><i class="fa fa-envelope fa-fw w3-margin-right w3-text-theme"></i>{{email}}</p>
              <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{alamat}}</p>
              <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i>{{tgl_lahir}}</p>
              <p><i class="fa fa-phone fa-fw w3-margin-right w3-text-theme"></i>{{no_hp}}</p>
                <div class="w3-container">
                  <p>Skills:</p>
                  <p>
                    {% for ii in keahlian %}
                    <span class="w3-tag w3-theme-d5">{{ii}}</span>
                    {% endfor %}
                  </p>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </content>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Sion_Controller/templates/profile/profile_sponsor.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-green.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style type="text/css">
    .coffee-icon{
    border-radius: 50%;
    margin-bottom: 10px;
    width: 10%;
    height: 10%;
    background-color: black;}
  </style>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <b class="">&nbsp;SION<br> </b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <a class="btn btn-primary"..PNG href="#">Pofile</a>
            <a class="btn btn-primary" href="#">Lihat Organisasi</a>
            <a class="btn btn-primary" href="#">Berdonasi ke Organisasi</a>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href="{% url 'Sion-Controller:auth_logout' %}">
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>&nbsp;Log Out</a>
        </div>
      </div>
    </nav>
  </header>

  <content style="color: black;">
    <div class="w3-container w3-content w3-round" style="margin-top: 50px; width: 600px;">
      <div class="w3-card w3-round w3-white">
        <div class="text-center">
          <div class="bg-primary">
            <h4 class="w3-center" style="margin-bottom: 20px; padding-top: 15px;">{{nama}}</h4>
            <p class="w3-center"><img src="{%static 'coffee icon.PNG' %}" class="w3-circle coffee-icon" style="height:106px;width:106px"></p>
            <div class="w3-theme-l4" style="height: auto; padding-top: 30px;">
              <p><i class="fa fa-envelope fa-fw w3-margin-right w3-text-theme"></i>{{email}}</p>
              <p style="padding-bottom: 15px;"><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{alamat}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </content>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>